version: "3"
services:
    app:
        restart: on-failure
        build: .
        depends_on:
            - postgres
        environment:
            DB_URL: postgres://hawkhacks:password@postgres:5432/hawkhacks_db
            NODE_ENV: development
            PORT: 3000
        ports:
            - "8080:8080"
        command: npm run dev
        volumes:
            - .:/app/
            - /app/node_modules

    postgres:
        image: postgres:11
        restart: on-failure
        healthcheck:
            test: ["CMD", "pg_isready", "-q", "-d", "postgres", "-U", "root"]
            timeout: 45s
            interval: 10s
            retries: 10
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: password
            POSTGRES_DB: db
            APP_DB_USER: hawkhacks
            APP_DB_PASSWORD: password
            APP_DB_NAME: hawkhacks_db
        volumes:
            - ./db/setup:/docker-entrypoint-initdb.d/
